ARG target_profile=tx-small

FROM eagleoutice/lithie-${target_profile}-base:latest

LABEL version="1.0" author="Florian Sihler" git="https://github.com/EagleoutIce/lithie-docker"

# Profile
ARG target_profile=tx-small

ENV openout_any='a' PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 max_print_line=1000

COPY profiles/${target_profile}.profile profiles/${target_profile}.sh \
     /profiles/
COPY LICENSE sltx-dep.yaml update-docker.sh /

USER root

RUN chmod +x /update-docker.sh && /update-docker.sh ${target_profile}

USER lithie-user

CMD ["/bin/bash"]