# Profile
ARG target_profile=tx-small

FROM eagleoutice/lithie-${target_profile}-base:latest

LABEL version="1.0" author="Florian Sihler" git="https://github.com/EagleoutIce/lithie-docker"

COPY LICENSE sltx-dep.yaml update-docker.sh/


USER root

RUN chmod +x /update-docker.sh && /update-docker.sh ${target_profile}

USER lithie-user

CMD ["/bin/bash"]