name: Build docker-images
'on':
  push: 
    branches:  
      - master
  schedule:
    # every two days build automatically
    - cron: '0 0 2 * *'
jobs:
  build:
    strategy:
      matrix:
        scheme: [tx-small, tx-full]
    name: Build texlive using the ${{ matrix.scheme }}-Profile
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          lfs: false
          submodules: true

      - name: Build the image
        run: |
          docker build -t lithie-${{ matrix.scheme }} --build-arg target_profile=${{ matrix.scheme }} .

      - name: Test that the image installed correctly
        run: |
          docker run --rm lithie-${{ matrix.scheme }} pdflatex --version
          docker run --rm lithie-${{ matrix.scheme }} latexmk --version

      - name: Deploy the image
        run: |
          TAG="ghcr.io/EagleoutIce/lithie-${{ matrix.scheme }}"
          VERSION="$(date "+%Y%m%d")"
          docker tag lithie-${{ matrix.scheme }} ${TAG}:$VERSION
          docker tag lithie-${{ matrix.scheme }} ${TAG}:latest
          docker images $TAG
          echo ${{ secrets.GHCR_IO }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push $TAG